### ISSUE TITLE
TypeScript support for SFCs

### ISSUE THREAD

**Issue by ltennstedt** [atom-ide-community/atom-ide-vue#3]
Atom version: 1.40.1 x64
Data Tip version: 0.11.0
Signature Help version: 0.7.1
Go to Definition version: 0.3.2
linter version: 2.3.1
ide-typescript: 0.9.1
atom-ide-vue: 1.1.0
language-vue: 0.25.0
OS: Linux

TypeScript in Vue's Single File Fomponents doesn't seem to work. Is this feature planned for the future?

Thanks for your time and work so far.

**Comment by Belar** [comment]
Hi @ltennstedt,
that's correct, unfortunately, TypeScript support in Vue's SFCs is not available.

> Is this feature planned for the future?

In short, yes.

It's a feature often requested in packages which add(ed) Vue support to Atom, as well as in TypeScript packages. It's been a while since I researched it, but if recall correctly it's tricky to add due to the way Atom handles scopes, multi-grammar files - couldn't find source for it now, only vaguely remember an issue thread.

That said, I remember getting some elements of TypeScript working in `.vue` files, so if time allows will give it another try.

**Comment by ltennstedt** [comment]
Thanks for the quick response @Belar,

so I will be patient. It's a pity that I can't help you at the moment.

I'm a java developer and am currently trying to learn the frontend or JavaScript development in general and to get my feet wet but they're still pretty dry. I appreciate your work and your commitment to filling the gap left by Facebook.

**Comment by Belar** [comment]
It took a while, but I'm happy to say that the package now supports TypeScript (validation in general).

> currently trying to learn the frontend or JavaScript development [...] can help testing commits and PRs from an end user perspective if that's helpful for you

That's awesome, I hope the dive into JavaScript is going strong and TypeScript support will come handy. Also, the more testing hands the better.

> I appreciate your work

You are very welcome. Thanks for patience.
